# Generated by Django 5.2.8 on 2025-11-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('level', models.IntegerField()),
                ('time_minutes', models.IntegerField()),
            ],
        ),
    ]
