# Generated by Django 5.2.8 on 2026-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
