# Generated by Django 5.2.8 on 2026-04-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код формулы')),
                ('name', models.CharField(max_length=255, verbose_name='Название формулы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подтема')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
                'ordering': ['topic__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='taskbank.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['subject__name', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=7, verbose_name='Класс')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Лёгкая'), (2, 'Средняя'), (3, 'Сложная')], default=1, verbose_name='Сложность')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Источник')),
                ('source_number', models.CharField(blank=True, max_length=50, verbose_name='Номер в источнике')),
                ('task_type', models.CharField(choices=[('theory', 'Теория / определение'), ('template_only', 'Шаблон без формулы'), ('template_formula', 'Шаблон + формула'), ('proof', 'Доказательство'), ('geometry_tikz', 'Геометрия с чертежом'), ('custom_generator', 'Кастомный генератор')], default='template_formula', max_length=30, verbose_name='Тип задачи')),
                ('task_template', models.TextField(verbose_name='Текст задачи')),
                ('solution_template', models.TextField(blank=True, verbose_name='Решение / ответ')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Например: {"a": [4,5,6], "h": [3,4,5]}', verbose_name='Параметры (JSON)')),
                ('custom_generator_name', models.CharField(blank=True, max_length=100, verbose_name='Имя кастомного генератора')),
                ('tikz_template', models.TextField(blank=True, verbose_name='TikZ шаблон')),
                ('time_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='Время (мин.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskbank.formula', verbose_name='Формула')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskbank.subject', verbose_name='Предмет')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='taskbank.subtopic', verbose_name='Подтема')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskbank.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['grade', 'subject__name', 'topic__name', 'title'],
            },
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='taskbank.topic', verbose_name='Тема'),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'name')},
        ),
    ]
