# Generated by Django 5.2.8 on 2026-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='drawing_type',
            field=models.CharField(choices=[('none', 'Без чертежа'), ('triangle', 'Треугольник'), ('segment', 'Отрезок'), ('adjacent_angles', 'Смежные углы'), ('vertical_angles', 'Вертикальные углы'), ('rectangle', 'Прямоугольник')], default='none', max_length=50, verbose_name='Тип чертежа'),
        ),
    ]
